### ISSUE TITLE
Bluecube Discussions

### ISSUE THREAD

**Issue by npxl32** [BlueCube-Games-Entertainment/rules#12]
This is where discussions for Bluecube go in a somewhat professional manner.
Talk about future plans, or request a pull request to be merged, etc.

**Comment by npxl32** [comment]
We have a crappy tutorial @saverofthewos imma make a better one asap which could mean today or tomorrow or 2 days from now due to limits

**Comment by npxl32** [comment]
@saverofthewos

**Comment by saverofthewos** [comment]
oog

**Comment by npxl32** [comment]
You can make people co-owner even in the free version: https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/maintaining-ownership-continuity-for-your-organization

**Comment by saverofthewos** [comment]
You can't make custom roles.

**Comment by npxl32** [comment]
What do you mean? The docs said it applied to the free version, are the docs outdated?

**Comment by saverofthewos** [comment]
Co-owner would be somewhat of a security issue if everyone had it, and custom roles cost money.

**Comment by saverofthewos** [comment]
https://github.com/BlueCube-Games-Entertainment/rules/discussions/20

**Comment by saverofthewos** [comment]
see https://github.com/BlueCube-Games-Entertainment/rules/discussions/ for discussions.
