### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by npxl32** [BlueCube-Games-Entertainment/rules#18]
Your images don't work because your fork is private or deleted or something. Put the images in the "READMEmedia" and then link to them there like how I linked to them when I added an image to the README.

**Comment by npxl32** [comment]
Check the "code" section of the README.

**Comment by saverofthewos** [comment]
The images work for me? Anyway, if they don't work, they are gone, I don't have access to them.

**Comment by npxl32** [comment]
Log out and see if they work.

**Comment by saverofthewos** [comment]
I don't know how I could fix that.
Although, the tutorial is probably clear enough to not need images.
