### ISSUE TITLE
PRIVATE FORKS: SUPER DUPER IMPORTANT ISSUE

### ISSUE THREAD

**Issue by npxl32** [BlueCube-Games-Entertainment/rules#19]
IMPORTANT:
"For security reasons you cannot make a fork private if the original is public, or private if the original is public."
This means no one can make a private fork of a public repository.

**Comment by npxl32** [comment]
@saverofthewos

**Comment by npxl32** [comment]
Possible workaround: https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private

**Comment by saverofthewos** [comment]
That rule is only for forks of unfinished games.
