### ISSUE TITLE
No profile README or website

### ISSUE THREAD

**Issue by npxl32** [BlueCube-Games-Entertainment/rules#3]
Simple, we need to make a profile README and a website. (The website can use a temporary design or I can just go straight to the final design.)

**Comment by npxl32** [comment]
Yes, I will host Prototype 1 of my website, happening today afternoon, then I will get to work creating Bluecube website.

**Comment by saverofthewos** [comment]
Theres already a repository for the bluecube website, called BLUECUBE, and its hosted at
saverofthewo.github.io/bluecube

**Comment by saverofthewos** [comment]
correction, https://saverofthewos.github.io/Bluecube/

**Comment by npxl32** [comment]
I have completed the website and am figuring out the pricing plans and the hosting. Will probably finish by today, worst case scenario, tomorrow.

**Comment by saverofthewos** [comment]
or it could run on saverofthewos/bluecube

**Comment by npxl32** [comment]
No I mean it will use the Blazor framework. You know how my Github pages site redirects to another website? This is because Github pages is for static websites (aka, websites that are just HTML files) and Bluecube needs a dynamically hosted website. This gives us a server that generates the HTML dynamically. Instead of simply serving HTML files, the server can dynamically generate it. I probably didn't explain this well so look up "static website vs dynamic website"

**Comment by saverofthewos** [comment]
By "just html" do you mean no javascript? Because github.io 100% supports javascript.

**Comment by npxl32** [comment]
No that's not what I mean (I knew I explained it badly!! Sorry this is an error on my part) I mean that the website can only serve files. You upload your files and GitHub Pages serves them. That's a static website. Bluecube needs a dynamic website, which is when you create your _own_ server, and GitHub Pages doesn't let you do that.

**Comment by npxl32** [comment]
I'm mostly done with MY website prototype (which after updating it, I will work on Bluecube), However I am running into unexpected certificate issues, so I adjust MY website Prototype 1 date to: 5 days from now

**Comment by npxl32** [comment]
My website should be live: [www.npxl32.com](https://www.npxl32.com/)
I might not update it and go straight to Bluecube. Should we use GitHub Pages for Bluecube?

**Comment by npxl32** [comment]
By the way, https://www.[npxl32.com/DynamicFileJSON](https://www.npxl32.com/DynamicFileJSON) is an example of a dynamic website. There is no JavaScript that is generating this JSON file. It is being generated on the server (before the response is sent)

**Comment by saverofthewos** [comment]
sock the head hog is aqmazing

**Comment by npxl32** [comment]
yes sock is built different

**Comment by saverofthewos** [comment]
Bluecube.com is already registered. I suggest Bluecube.site

**Comment by npxl32** [comment]
bluecube.games?
also i dont wanna pay for another domain and more hosting, i really cant afford that

**Comment by saverofthewos** [comment]
Well it was your suggestion.
Bluecube.site is only 2 dollars / year.

**Comment by saverofthewos** [comment]
https://github.com/BlueCube-Games-Entertainment/rules/discussions/22 Discuss here.
