### ISSUE TITLE
Get keyboardCTRL

### ISSUE THREAD

**Issue by saverofthewos** [BlueCube-Games-Entertainment/rules#6]

**Comment by npxl32** [comment]
Are you gonna send an invite to keyboardctrl

**Comment by saverofthewos** [comment]
I did

**Comment by npxl32** [comment]
KeyboardCTRL will only join once they get a VPN, which is not this year.

**Comment by saverofthewos** [comment]
Why does he need a VPN?

**Comment by npxl32** [comment]
Check his profile comments, I can't really explain it

**Comment by saverofthewos** [comment]
someones on your website the GET requests are increasing more than im reloading
